### ISSUE TITLE
Purge breaks build

### ISSUE THREAD

**Issue by estevanmaito** [estevanmaito/windmill-dashboard-react#1]
`windmill-dashboard-react` version: `0.1.0-alpha.1`

### Relevant code or config:

The content of the `require`d theme: [windmill-react-ui defaultTheme](https://github.com/estevanmaito/windmill-react-ui/blob/master/src/themes/default.js)

This projects [tailwind.config.js](https://github.com/estevanmaito/windmill-dashboard-react/blob/master/tailwind.config.js)
```js
const windmillTheme = require('windmill-react-ui/defaultTheme')

module.exports = {
  purge: ['src/**/*.js', windmillTheme],
```

### What you did:

`npm run build`

### What happened:

```sh
TypeError: Cannot read property 'match' of undefined
    at defaultExtractor (D:\windmill-dashboard-react\node_modules\tailwindcss\lib\lib\purgeUnusedStyles.js:93:36)
    at m (D:\windmill-dashboard-react\node_modules\purgecss\lib\purgecss.js:1:3149)
    at x.extractSelectorsFromString (D:\windmill-dashboard-react\node_modules\purgecss\lib\purgecss.js:1:5350)
    at D:\windmill-dashboard-react\node_modules\@fullhuman\postcss-purgecss\lib\postcss-purgecss.js:1:536
```

### Problem description:

Apparently `purge` doesn't accept an object of styles, but the problem also persists when trying something like:

```js
purge: ['src/**/*.js', 'node_modules/windmill-react-ui/lib/default.js'],
```

But in this case, instead of an Error, it results in a CSS build without the classes from the `default.js` files.

**Comment by estevanmaito** [comment]
The new strategy of encapsulating the Tailwind config object solves this.
